package com.biprom.eriks.telem.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Slider;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HardwareDesign extends Panel {
	protected CssLayout root_layout;
	protected Label billing_header_label;
	protected CssLayout main_content_wrapper;
	protected FormLayout billing_form;
	protected Label email_header_label;
	protected Slider digoutSlider;
	protected Label address_label;
	protected Slider diginSlider;
	protected Label address_label2;
	protected HorizontalLayout name_wrapper2;
	protected Slider anainpSlider;
	protected Label address_label3;
	protected Slider anaoutputSlider;
	protected Button configurationButton;
	protected Label billing_header_label2;
	protected Grid grid;
	protected Button hardwareButton;

	public HardwareDesign() {
		Design.read(this);
	}
}
